---
title: "Leow semester project"
author: "Chi-Jing Leow"
date: "2025-12-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE)
```


```{r, message=FALSE, warning=FALSE}
library(Seurat)
library(dplyr)
library(ggplot2)
library(monocle3)
library(patchwork)
library(glmGamPoi)
library(ggrepel)
library(plyr)
```


load monocle 3 object for 11dpf
```{r}
embryo_11dpf <- load_monocle_objects("data/embryo_11dpf")
```

convert to seurat object
```{r, message=FALSE, warning=FALSE}
counts_11dpf <- counts(embryo_11dpf)
metadata_11dpf <- as.data.frame(colData(embryo_11dpf))

seurat_obj_11dpf <- CreateSeuratObject(
counts = counts_11dpf,
meta.data = metadata_11dpf,
project = "GarEmbryo_11dpf")
```

normalize using SCTransform and run PCA, visualize PCs in elbow plot
```{r}
seurat_obj_11dpf <- SCTransform(seurat_obj_11dpf, verbose = FALSE)
seurat_obj_11dpf <- RunPCA(seurat_obj_11dpf, npcs = 30)

ElbowPlot(seurat_obj_11dpf, ndims = 40)

seurat_obj_11dpf <- FindNeighbors(seurat_obj_11dpf, dims = 1:20)
seurat_obj_11dpf <- FindClusters(seurat_obj_11dpf, resolution = 1.0)
seurat_obj_11dpf <- RunUMAP(seurat_obj_11dpf, dims = 1:20)

```

UMAP visualization
```{r}
DimPlot(seurat_obj_11dpf, group.by = "seurat_clusters", label = TRUE) +
ggtitle("11 dpf Gar – Clusters")
```
find marker genes
```{r, message=FALSE, warning=FALSE}
markers_11dpf <- FindAllMarkers(
seurat_obj_11dpf,
only.pos = TRUE,
min.pct = 0.25,
logfc.threshold = 0.25
)

top_markers_11dpf <- markers_11dpf %>%
group_by(cluster) %>%
top_n(n = 50, wt = avg_log2FC)

#write.csv(top_markers_11dpf, "top_markers_11dpf.csv", row.names = FALSE)
```

potential markers
```{r}
marker_genes <- list(
  `Neuron` = c("map2", "rbfox3", "elavl3", "elavl4"),
  `GABAergic neuron` = c("gad1", "gad2"),
  `Glutamatergic neuron` = c("slc17a6", "LOC107076130"),
  `motor_neuron` = c("chata"),
  `Vasculature` = c("stab1", "stab2", "flt4", "mrc1"),
  `Hepatocytes` = c("LOC102693614", "cp", "tfa"),
  `periderm` = c("nos1", "krt5", "ppl", "evpla", "grhl1"),
  `mucous secreting cell` = c("fer1l6", "muc5.1"),
  `multi-ciliated cell` = c("dnaaf6"),
  `melanocyte` = c("slc45a2", "trpm1a"),
  `pronephros` = c('slc4a2a', 'exoc3l2b'),
  `retinal_ganglion_cells` = c("ebf2", "ebf3a"),
  `fin_epidermis_1` = c("vit", "lamb4", "col28a2a"),
  `fin_epidermis_2` = c("fras1", "itih5", "ecm2"),
  `olfactory_sensory_cell` = c("LOC102682577", "nrsn1", "fstl5"),
  `retinal_bipolar_cell` = c("dscaml1", "gnb3a", "gnao1a", "ndrg4", "cabp2a"),
  `Fibroblast` = c("col1a1b", "col1a2", "col11a1a", "col14a1a"),
  `Ionocyte` = c("dscaml", "sdk1a", "trpv6", "gcm2", "sox10"),
  `Cilia` = c("dnah9", "dnah5l", "cfap299", "dnah7", "pkhd1l1.1"),
  `mesenchyme` = c("col5a1", "col6a3", "bnc2", "col1a1b", "col1a2"),
  `notochord` = c("col9a3", "col9a1b", "col11a1a"),
  `Glia` = c("gpm6bb"),
  `Muscle` = c("ttn.2", "actc1a", "neb"),
  `Erythrocytes` = c("cahz", "LOC102693769", "LOC102692770", "LOC102693166", "LOC102686312"),
  `Photoreceptor` = c("gngt2b", "gnb3b", "gnb3a", "prph2a"),
  `Enteric_neuron` = c("hand2", "LOC102691681"),
  `Heart` = c("LOC107075535", "gata5", "tgm2b", "LOC102692205")
)

#filter marker genes only present in seurat obj
marker_genes_filtered <- lapply(marker_genes, function(genes) {
  intersect(genes, rownames(seurat_obj_11dpf))
})
```

broad-lineage cell type annotation
```{r}
New_ident_11dpf_broad <- setNames(
  c(
    "Mesoderm (skeletal muscle)",                  # ryr3, neb, ttn.2, mef2cb, dmd
    "Mesoderm (cartilage-like mesenchyme)",        # col1a1b
    "Neural ectoderm (CNS neuron)",                # nrxn1a, adgrl1a, gabra2a, camta1a, lsamp
    "Mesoderm (muscle)",                           # myoz1a, actc2, tpm1, ckma, myl1
    "Neural ectoderm (CNS neuron, grin2aa+)",      # grin2aa, ryr1b, jph1a, neb, ttn.2
    "Mesoderm (muscle)",                           # tpm1, myl1, ckma, actc1a, eno1a
    "Mesoderm (cardiac muscle)",                   # myh7ba, mybpc1, myom3, tnnc1b, tnni1a
    "Neural crest / PNS glia (NMJ-associated)",    # pmp22b, xirp2b, klhl31, pdlim7, actc1a
    "Non-neural ectoderm (multiciliated epithelium)", # pkhd1l1.1, dnah9, dnah5l, dync2h1, cfap299
    "Mesoderm (fibro-adipogenic / tendon mesenchyme)" # tpm4a, myl4, pdgfc, itga9, adipoqa
  ),
  0:9  # cluster IDs at 11 dpf
)


```

```{r}
New_ident_11dpf_fine <- setNames(
  c(
    "Skeletal muscle (fast-twitch trunk)",              # ryr3, neb, ttn.2, mef2cb, dmd
    "Cartilage / fibrocartilage-like mesenchyme",       # col1a1b
    "CNS neuron (synaptic adhesion–rich)",              # nrxn1a, adgrl1a, gabra2a, camta1a, lsamp
    "Myofiber / sarcomeric muscle",                     # myoz1a, actc2, tpm1, ckma, myl1
    "CNS neuron (grin2aa+ spinal/brain)",               # grin2aa, ryr1b, jph1a, neb, ttn.2
    "Skeletal muscle (sarcomeric, mixed fiber type)",   # tpm1, myl1, ckma, actc1a, eno1a
    "Cardiomyocyte (ventricular/slow muscle)",          # myh7ba, mybpc1, myom3, tnnc1b, tnni1a
    "Peripheral glia / NMJ-associated Schwann-like",    # pmp22b, xirp2b, klhl31, pdlim7, actc1a
    "Multiciliated epithelial cell",                    # pkhd1l1.1, dnah9, dnah5l, dync2h1, cfap299
    "Wnt+ fibro-adipogenic / tendon mesenchyme"         # tpm4a, myl4, pdgfc, itga9, adipoqa
  ),
  0:9  # cluster IDs at 11 dpf
)

```

save original ident and assign new labels to metadata
```{r}
# save original ident
seurat_obj_11dpf$orig_cluster <- Idents(seurat_obj_11dpf)

# assign fine labels
seurat_obj_11dpf$New_ident <- plyr::mapvalues(
  x    = as.character(seurat_obj_11dpf$orig_cluster),
  from = names(New_ident_11dpf_fine),
  to   = unname(New_ident_11dpf_fine)
)

# set Idents to new annotation
Idents(seurat_obj_11dpf) <- "New_ident"
```

plot UMAP with annotated cell types
```{r}
DimPlot(seurat_obj_11dpf, label = TRUE) + ggtitle("11dpf annotated cell type") +
  theme(
    plot.title = element_text(size = 10, hjust = 0.5),     # smaller centered title
    axis.title = element_text(size = 8),                   # smaller axis titles
    axis.text = element_text(size = 7),                    # smaller tick labels
    legend.text = element_text(size = 7),                  # smaller legend text
    legend.title = element_text(size = 8),
    plot.margin = margin(5, 5, 5, 5)
  ) +
  theme(text = element_text(size = 8)) +
  theme(legend.position = "none")
```

```{r}

```